name: dart_code
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: pawankumar <email@example.com>

environment:
  sdk: '>=2.0.0-dev.62.0 <3.0.0'

dependencies:
  rxdart:
#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.30
